---
title: "Report on Recommender System"
author: "Juanelle Marks"
date: "11/7/2018"
output: html_document
---

#Question
>Your task is to analyze an existing recommender system that you find interesting.  You should:

>Perform a Scenario Design analysis as described below.  Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization's customers.
Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.
Include specific recommendations about how to improve the site's recommendation capabilities going forward. 
Create your report using an R Markdown file, and create a discussion thread with a link to the GitHub repo where your Markdown file notebook resides.  You are not expected to need to write code for this discussion assignment.

#Response
An existing recommender system that i find interesting is the one used by Netflix. According to an article by Busines Insider UK, "Netflix's most important metric  now is what you're most likely to watch and stick with for awhile".(http://uk.businessinsider.com/how-netflix-recommendations-work-2016-9). Hence, Netflix bases its recommendations on the frequency and length of time spent by  a customer watching  certain types of movies or tv shows.

The target users of this site are tv lovers, persons who love to spend some of their time watching a movie or tv show. The key goal of the target user  is to be able to view a movie or show  which appeals to their interest.  The site strives to help users achieve this goalm throuagh the current recommendation algorithms used.




